version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - echo "Running tests..."
      - pytest tests > test-report.log || true
  build:
    commands:
      - echo "Building app artifact..."
      - zip -r app.zip app run.py requirements.txt Dockerfile entrypoint.sh migrations .ebextensions

artifacts:
  files:
    - app.zip
  name: app-artifact
