version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Packaging app..."
      - zip -r app.zip . -x "*.git*"
artifacts:
  files:
    - app.zip
  name: app-artifact
